routes/web.php
<?php

use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/// Auth routes ///
Auth::routes();
/// Base routes ///
Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/faq','HomeController@faq')->name('faq');

/// Ammo routes ///
// ** Route::resource('ammo', 'AmmoController');
/* ||Ammo *** Non-AuthRoute|| */
Route::prefix('ammo')->name('ammo.')->group(function () {
  Route::get('/', 'AmmoController@index')->name('index');
/** ||Ammo *** AuthRoute|| **/
  Route::middleware('auth')->group(function () {
    Route::get('/create', 'AmmoController@create')->name('create');
    Route::post('/', 'AmmoController@store')->name('store');
    Route::get('{slug}/edit', 'AmmoController@edit')->name('edit');
    Route::put('/{slug}', 'AmmoController@update')->name('update');
    Route::delete('/{slug}', 'AmmoController@destroy')->name('destroy');
    //My Routes
    Route::get('/historial', 'AmmoController@historial')->name('history');
    Route::patch('/{slug}/activate', 'AmmoController@activate')->name('activate');
    Route::patch('/{slug}/deactivate', 'AmmoController@deactivate')->name('deactivate');
    Route::get('/{slug}/preview', 'AmmoController@preview')->name('preview');
  });
  Route::get('/{slug}', 'AmmoController@show')->name('show');
});

/// Armor routes ///
Route::prefix('armor')->group(function () {
  Route::get('/', 'ArmorController@index');
  Route::get('/{slug}', 'ArmorController@show');
});
/* AuthRoute */
Route::prefix('armor')->group(function () {
  Route::get('/create', 'ArmorController@create');
  Route::post('/', 'ArmorController@store');
  Route::get('{slug}/edit', 'ArmorController@edit');
  Route::put('/{slug}', 'ArmorController@update');
  Route::delete('/{slug}', 'ArmorController@destroy');
  //My Routes
  Route::get('/historial', 'ArmorController@historial');
  Route::patch('/{slug}/activate', 'ArmorController@activate');
  Route::patch('/{slug}/deactivate', 'ArmorController@deactivate');
  Route::get('/{slug}/preview', 'ArmorController@preview');
});

/// Item routes ///
Route::prefix('item')->group(function () {
  Route::get('/', 'ItemController@index');
  Route::get('/{slug}', 'ItemController@show');
});
/* AuthRoute */
Route::prefix('item')->group(function () {
  Route::get('/create', 'ItemController@create');
  Route::post('/', 'ItemController@store');
  Route::get('{slug}/edit', 'ItemController@edit');
  Route::put('/{slug}', 'ItemController@update');
  Route::delete('/{slug}', 'ItemController@destroy');
  //My Routes
  Route::get('/historial', 'ItemController@historial');
  Route::patch('/{slug}/activate', 'ItemController@activate');
  Route::patch('/{slug}/deactivate', 'ItemController@deactivate');
  Route::get('/{slug}/preview', 'ItemController@preview');
});

/// NPC routes ///
Route::prefix('npc')->group(function () {
  Route::get('/', 'NpcController@index');
  Route::get('/{slug}', 'NpcController@show');
});
/* AuthRoute */
Route::prefix('npc')->group(function () {
  Route::get('/create', 'NpcController@create');
  Route::post('/', 'NpcController@store');
  Route::get('{slug}/edit', 'NpcController@edit');
  Route::put('/{slug}', 'NpcController@update');
  Route::delete('/{slug}', 'NpcController@destroy');
  //My Routes
  Route::get('/historial', 'NpcController@historial');
  Route::patch('/{slug}/activate', 'NpcController@activate');
  Route::patch('/{slug}/deactivate', 'NpcController@deactivate');
  Route::get('/{slug}/preview', 'NpcController@preview');
});

/// Rarity routes ///
Route::prefix('rarity')->group(function () {
  Route::get('/', 'RarityController@index');
  Route::get('/{slug}', 'RarityController@show');
});
/* AuthRoute */
Route::prefix('rarity')->group(function () {
  Route::get('/create', 'RarityController@create');
  Route::post('/', 'RarityController@store');
  Route::get('{slug}/edit', 'RarityController@edit');
  Route::put('/{slug}', 'RarityController@update');
  Route::delete('/{slug}', 'RarityController@destroy');
  //My Routes
  Route::get('/historial', 'RarityController@historial');
  Route::patch('/{slug}/activate', 'RarityController@activate');
  Route::patch('/{slug}/deactivate', 'RarityController@deactivate');
  Route::get('/{slug}/preview', 'RarityController@preview');
});

/// Skill routes ///
Route::prefix('skill')->group(function () {
  Route::get('/', 'SkillController@index');
  Route::get('/{slug}', 'SkillController@show');
});
/* AuthRoute */
Route::prefix('skill')->group(function () {
  Route::get('/create', 'SkillController@create');
  Route::post('/', 'SkillController@store');
  Route::get('{slug}/edit', 'SkillController@edit');
  Route::put('/{slug}', 'SkillController@update');
  Route::delete('/{slug}', 'SkillController@destroy');
  //My Routes
  Route::get('/historial', 'SkillController@historial');
  Route::patch('/{slug}/activate', 'SkillController@activate');
  Route::patch('/{slug}/deactivate', 'SkillController@deactivate');
  Route::get('/{slug}/preview', 'SkillController@preview');
});

/// Stat routes ///
Route::prefix('stat')->group(function () {
  Route::get('/', 'StatController@index');
  Route::get('/{slug}', 'StatController@show');
});
/* AuthRoute */
Route::prefix('stat')->group(function () {
  Route::get('/create', 'StatController@create');
  Route::post('/', 'StatController@store');
  Route::get('{slug}/edit', 'StatController@edit');
  Route::put('/{slug}', 'StatController@update');
  Route::delete('/{slug}', 'StatController@destroy');
  //My Routes
  Route::get('/historial', 'StatController@historial');
  Route::patch('/{slug}/activate', 'StatController@activate');
  Route::patch('/{slug}/deactivate', 'StatController@deactivate');
  Route::get('/{slug}/preview', 'StatController@preview');
});

/// Weapon routes ///
Route::prefix('weapon')->group(function () {
  Route::get('/', 'WeaponController@index');
  Route::get('/{slug}', 'WeaponController@show');
});
/* AuthRoute */
Route::prefix('weapon')->group(function () {
  Route::get('/create', 'WeaponController@create');
  Route::post('/', 'WeaponController@store');
  Route::get('{slug}/edit', 'WeaponController@edit');
  Route::put('/{slug}', 'WeaponController@update');
  Route::delete('/{slug}', 'WeaponController@destroy');
  //My Routes
  Route::get('/historial', 'WeaponController@historial');
  Route::patch('/{slug}/activate', 'WeaponController@activate');
  Route::patch('/{slug}/deactivate', 'WeaponController@deactivate');
  Route::get('/{slug}/preview', 'WeaponController@preview');
});

app/Ammo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Ammo extends Model{

  public function weapons(){
    return $this->belongsToMany('App\Weapon');
  }
  public function item(){
    return $this->morphToMany('App\Item', 'itemable');
  }

}

app/Http/Controllers/AmmoController.php
<?php

namespace App\Http\Controllers;

use App\Ammo;
use Illuminate\Http\Request;

class AmmoController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index(){
    $ammos = Ammo::All();
    
    $VAC = compact('ammos');
    return view('ammo.index', $VAC);
  }
  
  /**
  * Display the specified resource.
  *
  * @param  \App\slug  $slug
  * @return \Illuminate\Http\Response
  */
  public function show(string $slug){
    $ammo = Ammo::where('slug', $slug)->first();
    
    return view('ammo.show', compact('ammo'));
  }
  
  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create(){
    return view('ammo.new');
  }
  
  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Request $request){
    $rules = [
      "name" => "required|bail|string",
      "weight" => "required|numeric",
      "description" => "required|string",
      "img" => "required|image",
    ];

    $message = [
      "required" => "El campo :attribute es requerido",
      "unique" => "El :attribute ya existe en nuestra Base de Datos",
      "image" => ":attribute tiene que ser una imagen",
      "numeric" => ":attribute deberia ser un numero",
    ];
    
    $this->validate($request, $rules, $message);
    
    $ammo = new Ammo();
    
    $ammoImg = $request->file("img");
    $ammoImgPath = $ammoImg->storePublicly("public/ammo/img");
    $ammoImgPath = str_replace("public", "storage", $ammoImgPath);
    
    $ammo->name = $request["name"];
    $ammo->slug = str_slug($request["name"]);
    $ammo->weight = $request["weight"];
    $ammo->description = $request["description"];
    $ammo->img = $ammoImgPath;
    $ammo->status = 0;
    //$ammo->owner_id = Auth::user()->id;
    
    $ammo->save();

    $VAC = compact('ammo');
    return view('ammo.preview', $VAC);
  }
  
  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\slug  $slug
  * @return \Illuminate\Http\Response
  */
  public function edit(string $slug){
    $ammo = Ammo::where('slug', $slug)->first();
    $VAC = compact('ammo');
    return view('ammo.edit', $VAC);
  }
  
  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\slug  $slug
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, slug $slug){
    $ammo = Ammo::find($slug);

    $rules = [
    "name" => "required|bail|string",
    "weight" => "required|numeric",
    "description" => "required|string",
    "img" => "required|image",
    ];

    $mesage = [
        "required" => "El campo :attribute es requerido",
        "unique" => "El :attribute ya existe en nuestra Base de Datos",
        "image" => ":attribute tiene que ser una imagen",
        "numeric" => ":attribute deberia ser un numero",
    ];

    $this->validate($request, $reglas, $mensajes);


    $ammoImg = $request->file("photo");
    $ammoImgPath = $ammoImg->storePublicly("public/ammo/photo");
    $ammoImgPath = str_replace("public", "storage", $ammoImgPath);

    $ammo->name = $request["name"];
    $ammo->slug = str_slug($request["name"]);
    $ammo->weight = $request["weight"];
    $ammo->description = $request["description"];
    $ammo->img = $prodImgPath;

    $ammo->save();
    $VAC = compact('ammo');

    if($ammo->status === 0){
      return view('ammo.preview', $VAC);
    } elseif ($ammo->status === 0) {
      return view('ammo.show', $VAC);
    }
  }
  
  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Ammo  $slug
  * @return \Illuminate\Http\Response
  */
  public function destroy(string $slug)
  {
    // delete
    $ammo = Ammo::find($slug);
    $ammo->delete();

    // redirect //maybe fix?
    Session::flash('message', 'Successfully deleted the ammo!');
    return Redirect::to('ammos');
  }
  
  /**
  * Shows the ammos inactive.
  *
  * @return \Illuminate\Http\Response
  */
  public function historial()
  {
    $ammos = Ammo::orderBy('id', 'DESC')
    ->where('status', '=', '0')
    ->get();
    
    return view('ammo.history', compact('ammos'));
  }

  /**
  * Activates a deactive ammo.
  *
  * @param  \App\Ammo $slug
  * @return \Illuminate\Http\Response
  */
  public function activate(string $slug)
  {
    $ammo = Ammo::where('slug', $slug)->first();

    $ammo->status = 1;
    $ammo->save();

    return redirect("/ammo");
  }

  /**
   * Deactivates an active ammo.
   *
   * @param  \App\Ammo $slug
   * @return \Illuminate\Http\Response
   */
  public function deactivate(string $slug)
  {
    $ammo = Ammo::where('slug', $slug)->first();

    $ammo->status = 0;
    $ammo->save();

    return redirect("/ammo");
  }
}

resources/views/ammo/edit.blade.php
@extends('layouts.app')

@section('title')
| {{ $ammo->name }} Ammo Card (Preview)
@endsection

@section('content')

@include('ammo.nav')

<section class="cards-holder">
  <article class="card card-ammo">
    <a href="{{ url('ammo/'.$ammo->slug) }}">
      <h3>{{ $ammo->name }}</h3>
      <h6>{{ $ammo->weight }}</h6>
      <p>{{ $ammo->description }}</p>
      <img src="{{ $ammo->img }}" alt="{{ $ammo->name }} image">
    </a>
  </article>
</section>

	<div class="row">
		{!! Form::model($post, ['route' => ['posts.update', $post->id], 'method' => 'PUT']) !!}
		<div class="col-md-8">
			{{ Form::label('title', 'Title:') }}
			{{ Form::text('title', null, ["class" => 'form-control input-lg']) }}

			{{ Form::label('slug', 'Slug:', ['class' => 'form-spacing-top']) }}
			{{ Form::text('slug', null, ['class' => 'form-control']) }}
			
			{{ Form::label('body', "Body:", ['class' => 'form-spacing-top']) }}
			{{ Form::textarea('body', null, ['class' => 'form-control']) }}
		</div>

		<div class="col-md-4">
			<div class="well">
				<dl class="dl-horizontal">
					<dt>Created At:</dt>
					<dd>{{ date('M j, Y h:ia', strtotime($post->created_at)) }}</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>Last Updated:</dt>
					<dd>{{ date('M j, Y h:ia', strtotime($post->updated_at)) }}</dd>
				</dl>
				<hr>
				<div class="row">
					<div class="col-sm-6">
						{!! Html::linkRoute('posts.show', 'Cancel', array($post->id), array('class' => 'btn btn-danger btn-block')) !!}
					</div>
					<div class="col-sm-6">
						{{ Form::submit('Save Changes', ['class' => 'btn btn-success btn-block']) }}
					</div>
				</div>

			</div>
		</div>
		{!! Form::close() !!}
	</div>	<!-- end of .row (form) -->

@endsection

@section('scripts')

@endsection

resources/views/ammo/history.blade.php
@extends('layouts.app')

@section('title')
| All Ammo Cards Inactive
@endsection

@section('content')

@include('ammo.nav')

<section class="cards-holder">
  @foreach($ammos as $ammo)
  <article class="card card-ammo">
    <a href="{{ url('ammo/'.$ammo->slug) }}">
      <h3>{{ $ammo->name }}</h3>
      <h6>{{ $ammo->weight }}</h6>
      <p>{{ $ammo->description }}</p>
      <img src="{{ $ammo->img }}" alt="{{ $ammo->name }} image">
    </a>
  </article>
  @endforeach
</section>

@endsection

@section('scripts')

@endsection

resources/views/ammo/index.blade.php
@extends('layouts.app')

@section('title')
| All Ammo Cards
@endsection

@section('content')

@include('ammo.nav')

<section class="cards-holder">
  @foreach($ammos as $ammo)
  <a href="{{ url('ammo/'.$ammo->item()->slug) }}" class="card card-ammo 
  @if($ammo->item()->status === 0)
  inactive
  @endif
  ">
    <picture>
      <img src="{{ asset($ammo->item()->img) }}" alt="Image of {{ $ammo->item()->name }}">
    </picture>
    <h3>{{ $ammo->item()->name }}</h3>
    <h6>Weight: {{ $ammo->item()->weight }} wp</h6>
    <p>{{ $ammo->item()->description }}</p>
  </a>
  @endforeach
</section>


@include('ammo.nav')

<section class="hero">
  <article>
    <h4 class="hero-text ">
      Items
    </h4>
    <div class="pre">
      @forEach($items as $item)
      <div class="cosas" style="background-color:{{ $item->rarity->color }}">
        <h6>{{ $item->name }}</h6>
        <p>Slug: {{ $item->slug }}</p>
        <p>Weight: {{ $item->weight }}</p>
        <p>Rare ID: {{ $item->rarity_id }}</p>
        <p>Desc :{{ $item->description }}</p>
        <p>Effect: {{ $item->effect }}</p>
        <p>Img :{{ $item->img }}</p>
        <p>Status: {{ $item->status }}</p>
        <p>itemabled ID: {{ $item->itemable_id }}</p>
        <p>itemabled Type: {{ $item->itemable_type }}</p>
        <p>Created: {{ $item->created_at }}</p>
        <p>Updated: {{ $item->updated_at }}</p>
        <p>Itemize: {{ $item->itemable}}</p>
        {{-- <pre>
          @dump($item)
          @dump($item->rarity)
        </pre> --}}
        <p>Rarity: {{ $item->rarity->name }}</p>
        {{--
        --}}
      </div>
      @endforEach
    </div>
  </article>
</section>

@endsection

@section('scripts')

@endsection

resources/views/ammo/nav.blade.php
<nav class="ammo-nav">
  <a class="nav-link" href="{{ route('ammo.index') }}"> Ammos</a>
  <a class="nav-link" href="{{ route('ammo.create') }}"> New Ammos</a>
  <a class="nav-link" href="{{ route('ammo.history') }}"> Ammo History</a>
</nav>

resources/views/ammo/new.blade.php
@extends('layouts.app')

@section('title')
| New Ammo Card
@endsection

@section('content')

@include('ammo.nav')

<section class="cards-holder">
  <article class="card card-ammo">
    <input type="text"> <h3> name </h3>
    <input type="text"> <h6> weight </h6>
    <input type="text"> <p> description </p>
    <input type="text"><img src="{{ asset('img/FoT_Bend_the_Rules.png') }}" alt="Placeholder image">
  </article>
</section>

{!! Form::open(array('route' => 'ammo.store', 'data-parsley-validate' => '', 'files' => true)) !!}
  {{ Form::label('name', 'Name:') }}
  {{ Form::text('name', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255')) }}

  {{ Form::label('weight', 'Weight:') }}
  {{ Form::number('weight', null, array('class' => 'form-control', 'required' => '') ) }}

  {{ Form::label('description', "Description:") }}
  {{ Form::textarea('description', null, array('class' => 'form-control','required' => '')) }}

  {{ Form::label('img', 'Upload a Image') }}
  {{ Form::file('img',['required' => '']) }}


  {{ Form::submit('Create Ammo Card', array('class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top: 20px;')) }}
{!! Form::close() !!}

@endsection

@section('scripts')

@endsection

resources/views/ammo/preview.blade.php
@extends('layouts.app')

@section('title')
| {{ $ammo->name }} Ammo Card (Preview)
@endsection

@section('content')

@include('ammo.nav')

<section class="cards-holder">
  <article class="card card-ammo">
    <a href="{{ url('ammo/'.$ammo->slug) }}">
      <h3>{{ $ammo->name }}</h3>
      <h6>{{ $ammo->weight }}</h6>
      <p>{{ $ammo->description }}</p>
      <img src="{{ $ammo->img }}" alt="{{ $ammo->name }} image">
    </a>
  </article>
</section>

@endsection

@section('scripts')

@endsection

resources/views/ammo/show.blade.php
@extends('layouts.app')

@section('title')
| {{ $ammo->name }} Ammo Card
@endsection

@section('content')

@include('ammo.nav')

<section class="cards-holder">
  <article class="card card-ammo
  @if($ammo->status === 0)
  inactive
  @endif
  ">
    <a href="{{ url('ammo/'.$ammo->slug) }}">
      <picture>
        <img src="{{ asset($ammo->img) }}" alt="Image of {{ $ammo->name }}">
      </picture>
      <h3>{{ $ammo->name }}</h3>
      <h6>Weight {{ $ammo->weight }} WP</h6>
      <p>{{ $ammo->description }}</p>
    </a>
    <a href="{{ url('ammo/'.$ammo->slug.'/edit') }}">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M402.6 83.2l90.2 90.2c3.8 3.8 3.8 10 0 13.8L274.4 405.6l-92.8 10.3c-12.4 1.4-22.9-9.1-21.5-21.5l10.3-92.8L388.8 83.2c3.8-3.8 10-3.8 13.8 0zm162-22.9l-48.8-48.8c-15.2-15.2-39.9-15.2-55.2 0l-35.4 35.4c-3.8 3.8-3.8 10 0 13.8l90.2 90.2c3.8 3.8 10 3.8 13.8 0l35.4-35.4c15.2-15.3 15.2-40 0-55.2zM384 346.2V448H64V128h229.8c3.2 0 6.2-1.3 8.5-3.5l40-40c7.6-7.6 2.2-20.5-8.5-20.5H48C21.5 64 0 85.5 0 112v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V306.2c0-10.7-12.9-16-20.5-8.5l-40 40c-2.2 2.3-3.5 5.3-3.5 8.5z"/></svg>
    </a>
    <a href="{{ url('ammo/'.$ammo->slug.'/activate') }}">
      <svg aria-hidden="true" data-prefix="far" data-icon="toggle-on" class="svg-inline--fa fa-toggle-on fa-w-18" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M576 256c0 106.039-85.961 192-192 192H192C85.961 448 0 362.039 0 256S85.961 64 192 64h192c106.039 0 192 85.961 192 192zM384 112c-79.582 0-144 64.404-144 144 0 79.582 64.404 144 144 144 79.582 0 144-64.404 144-144 0-79.582-64.404-144-144-144"></path></svg>
    </a>
    <a href="{{ url('ammo/'.$ammo->slug.'/deactivate') }}">
      <svg aria-hidden="true" data-prefix="far" data-icon="toggle-off" class="svg-inline--fa fa-toggle-off fa-w-18" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M384 64H192C85.961 64 0 149.961 0 256s85.961 192 192 192h192c106.039 0 192-85.961 192-192S490.039 64 384 64zM48 256c0-79.583 64.404-144 144-144 79.582 0 144 64.404 144 144 0 79.582-64.404 144-144 144-79.582 0-144-64.404-144-144zm336 144h-65.02c86.704-76.515 86.683-211.504 0-288H384c79.582 0 144 64.404 144 144 0 79.582-64.404 144-144 144z"></path></svg>
    </a>
    <a href="{{ url('ammo/'.$ammo->slug.'/destroy') }}">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M0 84V56c0-13.3 10.7-24 24-24h112l9.4-18.7c4-8.2 12.3-13.3 21.4-13.3h114.3c9.1 0 17.4 5.1 21.5 13.3L312 32h112c13.3 0 24 10.7 24 24v28c0 6.6-5.4 12-12 12H12C5.4 96 0 90.6 0 84zm416 56v324c0 26.5-21.5 48-48 48H80c-26.5 0-48-21.5-48-48V140c0-6.6 5.4-12 12-12h360c6.6 0 12 5.4 12 12zm-272 68c0-8.8-7.2-16-16-16s-16 7.2-16 16v224c0 8.8 7.2 16 16 16s16-7.2 16-16V208zm96 0c0-8.8-7.2-16-16-16s-16 7.2-16 16v224c0 8.8 7.2 16 16 16s16-7.2 16-16V208zm96 0c0-8.8-7.2-16-16-16s-16 7.2-16 16v224c0 8.8 7.2 16 16 16s16-7.2 16-16V208z"/></svg>
    </a>

  </article>
</section>

@endsection

@section('scripts')

@endsection